DROP DATABASE IF EXISTS bank;
CREATE DATABASE bank;
USE bank;

CREATE TABLE Accounts (
	ID					INT				PRIMARY KEY		AUTO_INCREMENT,
	ACCOUNT_HOLDER		VARCHAR(50)		NOT NULL,
	BALANCE				decimal(9,2)	NOT NULL,
	FEES				decimal(9,2)	NOT NULL,
	USERNAME			varchar(15)		NOT NULL		UNIQUE
);

CREATE TABLE Transactions (
	ID					INT				PRIMARY KEY		AUTO_INCREMENT,
	AMOUNT				DECIMAL(9,2)	NOT NULL,
	TRANS_TYPE			VARCHAR(8)		NOT NULL,
    TRANS_DATE			DATE			NOT NULL,
	ACCOUNT_ID			INT				NOT NULL,
	FOREIGN KEY (ACCOUNT_ID) REFERENCES Accounts (ID)
);

DELIMITER //

CREATE TRIGGER update_account_balance
AFTER INSERT
   ON Transactions FOR EACH ROW 
BEGIN

	SET @curBal = (SELECT balance FROM accounts WHERE ID = NEW.account_id);
    SET @curFees = (SELECT fees FROM accounts WHERE ID = NEW.account_id);
    
	IF NEW.trans_type = "WITHDRAW" THEN
    
		IF (@curBal - NEW.amount) < 0 THEN
			UPDATE accounts SET 
            balance = (@curBal - NEW.amount),
            fees = (fees + 35)
			WHERE ID = NEW.account_id;
            
		ELSE
			UPDATE accounts SET 
            balance = (@curBal - NEW.amount)
			WHERE ID = NEW.account_id;        
		END IF;
        
	ELSE
            
		IF @curFees > 0 AND NEW.amount <= @curFees THEN
			UPDATE accounts SET
            fees = (@curFees - NEW.Amount)
            WHERE ID = NEW.account_id;
            
		ELSEIF @curFees > 0 AND NEW.amount > @curFees THEN
			UPDATE accounts SET
            fees = 0,
            balance = (@curBal + NEW.amount) - fees
            WHERE ID = NEW.account_id; 
            
        ELSE
			UPDATE accounts SET 
			balance = (@curBal + NEW.amount)
			WHERE ID = NEW.account_id;
		END IF;
        
	END IF;

END; //

DELIMITER ;

DELIMITER //

CREATE PROCEDURE add_check_user
(IN account_hol VARCHAR(50), bal DECIMAL(9,2), uname VARCHAR(15), amnt DECIMAL(9,2), transaction_type VARCHAR(8))
BEGIN

	IF EXISTS(SELECT id FROM accounts WHERE uname = username) THEN
		SET @uid = (SELECT id FROM accounts WHERE uname = username);
        INSERT INTO Transactions VALUES
        (NULL, amnt, transaction_type, get_random_date(25), @uid);        
        
	ELSE
		INSERT INTO accounts VALUES
        (NULL, account_hol, bal, 0, uname);
        SET @last_inserted_id = LAST_INSERT_ID();
        INSERT INTO Transactions VALUES
        (NULL, amnt, transaction_type, get_random_date(25), @last_inserted_id);        
	END IF;

END; //

DELIMITER ;


DELIMITER //

CREATE PROCEDURE get_user_transactions
(IN uname VARCHAR(15), IN get_all_users BOOLEAN)
BEGIN
	
    IF NOT get_all_users THEN
		SELECT account_holder, Transactions.amount, Transactions.trans_type, Transactions.trans_date FROM accounts
		LEFT OUTER JOIN Transactions ON Transactions.account_id=accounts.id
		WHERE accounts.username = uname
		ORDER BY trans_date DESC;
        
	ELSE 
		SELECT account_holder, Transactions.amount, Transactions.trans_type, Transactions.trans_date FROM accounts
		LEFT OUTER JOIN Transactions ON Transactions.account_id=accounts.id
        ORDER BY account_holder ASC, trans_date DESC;
		
    END IF;

END; //

DELIMITER ;


DELIMITER //

CREATE FUNCTION get_random_date
(start_year INT)
RETURNS DATE
NOT DETERMINISTIC
BEGIN
	DECLARE rand_date DATE;
    SET rand_date = (SELECT CURDATE() - INTERVAL RAND()*start_year YEAR - INTERVAL RAND()*365 DAY);
    RETURN rand_date;
    
END; //

DELIMITER ;

DELIMITER //

CREATE FUNCTION get_first_name
(first_name VARCHAR(25))
RETURNS VARCHAR(25)
NOT DETERMINISTIC
BEGIN
		SET first_name = ELT(FLOOR(RAND()*355)+1, 'AARON','ABDUL','ABE','ABEL','ABRAHAM','ABRAM','ADALBERTO','ADAM','ADAN','ADOLFO','ADOLPH','ADRIAN','AGUSTIN','AHMAD','AHMED','AL','ALAN','ALBERT','ALBERTO','ALDEN','ALDO','ALEC','ALEJANDRO','ALEX','ALEXANDER','ALEXIS','ALFONSO','ALFONZO','ALFRED','ALFREDO','ALI','ALLAN','ALLEN','ALONSO','ALONZO','ALPHONSE','ALPHONSO','ALTON','ALVA','ALVARO','ALVIN','AMADO','AMBROSE','AMOS','ANDERSON','ANDRE','ANDREA',
		'ANDREAS','ANDRES','ANDREW','ANDY','ANGEL','ANGELO','ANIBAL','ANTHONY','ANTIONE','ANTOINE','ANTON','ANTONE','ANTONIA','ANTONIO','ANTONY','ANTWAN','ARCHIE','ARDEN','ARIEL','ARLEN','ARLIE','ARMAND','ARMANDO','ARNOLD','ARNOLDO','ARNULFO','ARON','ARRON','ART','ARTHUR','ARTURO','ASA','ASHLEY','AUBREY','AUGUST','AUGUSTINE','AUGUSTUS','AURELIO','AUSTIN','AVERY','BARNEY','BARRETT','BARRY','BART','BARTON','BASIL','BEAU','BEN','BENEDICT','BENITO','BENJAMIN',
		'BENNETT','BENNIE','BENNY','BENTON','BERNARD','BERNARDO','BERNIE','BERRY','BERT','BERTRAM','BILL','BILLIE','BILLY','BLAINE','BLAIR','BLAKE','BO','BOB','BOBBIE','BOBBY','BOOKER','BORIS','BOYCE','BOYD','BRAD','BRADFORD','BRADLEY','BRADLY','BRADY','BRAIN','BRANDEN','BRANDON','BRANT','BRENDAN','BRENDON','BRENT','BRENTON','BRET','BRETT','BRIAN','BRICE','BRITT','BROCK','BRODERICK','BROOKS','BRUCE','BRUNO','BRYAN','BRYANT','BRYCE','BRYON','BUCK','BUD','BUDDY',
		'BUFORD','BURL','BURT','BURTON','BUSTER','BYRON','CALEB','CALVIN','CAMERON','CAREY','CARL','CARLO','CARLOS','CARLTON','CARMELO','CARMEN','CARMINE','CAROL','CARROL','CARROLL','CARSON','CARTER','CARY','CASEY','CECIL','CEDRIC','CEDRICK','CESAR','CHAD','CHADWICK','CHANCE','CHANG','CHARLES','CHARLEY','CHARLIE','CHAS','CHASE','CHAUNCEY','CHESTER','CHET','CHI','CHONG','CHRIS','CHRISTIAN','CHRISTOPER','CHRISTOPHER','CHUCK','CHUNG','CLAIR','CLARENCE','CLARK','CLAUD',
		'CLAUDE','CLAUDIO','CLAY','CLAYTON','CLEMENT','CLEMENTE','CLEO','CLETUS','CLEVELAND','CLIFF','CLIFFORD','CLIFTON','CLINT','CLINTON','CLYDE','CODY','COLBY','COLE','COLEMAN','COLIN','COLLIN','COLTON','COLUMBUS','CONNIE','CONRAD','CORDELL','COREY','CORNELIUS','CORNELL','CORTEZ','CORY','COURTNEY','COY','CRAIG','CRISTOBAL','CRISTOPHER','CRUZ','CURT','CURTIS','CYRIL','CYRUS','DALE','DALLAS','DALTON','DAMIAN','DAMIEN','DAMION','DAMON','DAN','DANA','DANE','DANIAL','DANIEL',
		'DANILO','DANNIE','DANNY','DANTE','DARELL','DAREN','DARIN','DARIO','DARIUS','DARNELL','DARON','DARREL','DARRELL','DARREN','DARRICK','DARRIN','DARRON','DARRYL','DARWIN','DARYL','DAVE','DAVID','DAVIS','DEAN','DEANDRE','DEANGELO','DEE','DEL','DELBERT','DELMAR','DELMER','DEMARCUS','DEMETRIUS','DENIS','DENNIS','DENNY','DENVER','DEON','DEREK','DERICK','DERRICK','DESHAWN','DESMOND','DEVIN','DEVON','DEWAYNE','DEWEY','DEWITT','DEXTER','DICK','DIEGO','DILLON','DINO','DION','DIRK',
		'DOMENIC','DOMINGO','DOMINIC','DOMINICK','DOMINIQUE','DON','DONALD','DONG','DONN','DONNELL','DONNIE','DONNY','DONOVAN','DONTE','DORIAN','DORSEY','DOUG','DOUGLAS','DOUGLASS','DOYLE','DREW','DUANE','DUDLEY','DUNCAN','DUSTIN','DUSTY','DWAIN','DWAYNE','DWIGHT','DYLAN','EARL','EARLE','EARNEST','ED','EDDIE','EDDY','EDGAR','EDGARDO','EDISON','EDMOND','EDMUND','EDMUNDO','EDUARDO');
		
        RETURN first_name;
        
END; //

DELIMITER ;

DELIMITER //

CREATE FUNCTION get_last_name
(last_name VARCHAR(25))
RETURNS VARCHAR(25)
NOT DETERMINISTIC
BEGIN
		SET last_name = ELT(FLOOR(RAND()*999)+1, 'SMITH', 'JOHNSON', 'WILLIAMS', 'BROWN', 'JONES', 'MILLER', 'DAVIS', 'GARCIA', 'RODRIGUEZ', 'WILSON', 'MARTINEZ', 'ANDERSON', 
        'TAYLOR', 'THOMAS', 'HERNANDEZ', 'MOORE', 'MARTIN', 'JACKSON', 'THOMPSON', 'WHITE', 'LOPEZ', 'LEE', 'GONZALEZ', 'HARRIS', 'CLARK', 'LEWIS', 'ROBINSON', 'WALKER', 'PEREZ', 
        'HALL', 'YOUNG', 'ALLEN', 'SANCHEZ', 'WRIGHT', 'KING', 'SCOTT', 'GREEN', 'BAKER', 'ADAMS', 'NELSON', 'HILL', 'RAMIREZ', 'CAMPBELL', 'MITCHELL', 'ROBERTS', 'CARTER', 'PHILLIPS', 
        'EVANS', 'TURNER', 'TORRES', 'PARKER', 'COLLINS', 'EDWARDS', 'STEWART', 'FLORES', 'MORRIS', 'NGUYEN', 'MURPHY', 'RIVERA', 'COOK', 'ROGERS', 'MORGAN', 'PETERSON', 'COOPER', 'REED', 
        'BAILEY', 'BELL', 'GOMEZ', 'KELLY', 'HOWARD', 'WARD', 'COX', 'DIAZ', 'RICHARDSON', 'WOOD', 'WATSON', 'BROOKS', 'BENNETT', 'GRAY', 'JAMES', 'REYES', 'CRUZ', 'HUGHES', 'PRICE', 'MYERS', 
        'LONG', 'FOSTER', 'SANDERS', 'ROSS', 'MORALES', 'POWELL', 'SULLIVAN', 'RUSSELL', 'ORTIZ', 'JENKINS', 'GUTIERREZ', 'PERRY', 'BUTLER', 'BARNES', 'FISHER', 'HENDERSON', 'COLEMAN', 'SIMMONS', 
        'PATTERSON', 'JORDAN', 'REYNOLDS', 'HAMILTON', 'GRAHAM', 'KIM', 'GONZALES', 'ALEXANDER', 'RAMOS', 'WALLACE', 'GRIFFIN', 'WEST', 'COLE', 'HAYES', 'CHAVEZ', 'GIBSON', 'BRYANT', 'ELLIS', 'STEVENS', 
        'MURRAY', 'FORD', 'MARSHALL', 'OWENS', 'MCDONALD', 'HARRISON', 'RUIZ', 'KENNEDY', 'WELLS', 'ALVAREZ', 'WOODS', 'MENDOZA', 'CASTILLO', 'OLSON', 'WEBB', 'WASHINGTON', 'TUCKER', 'FREEMAN', 'BURNS', 
        'HENRY', 'VASQUEZ', 'SNYDER', 'SIMPSON', 'CRAWFORD', 'JIMENEZ', 'PORTER', 'MASON', 'SHAW', 'GORDON', 'WAGNER', 'HUNTER', 'ROMERO', 'HICKS', 'DIXON', 'HUNT', 'PALMER', 'ROBERTSON', 'BLACK', 'HOLMES', 
        'STONE', 'MEYER', 'BOYD', 'MILLS', 'WARREN', 'FOX', 'ROSE', 'RICE', 'MORENO', 'SCHMIDT', 'PATEL', 'FERGUSON', 'NICHOLS', 'HERRERA', 'MEDINA', 'RYAN', 'FERNANDEZ', 'WEAVER', 'DANIELS', 'STEPHENS', 'GARDNER', 
        'PAYNE', 'KELLEY', 'DUNN', 'PIERCE', 'ARNOLD', 'TRAN', 'SPENCER', 'PETERS', 'HAWKINS', 'GRANT', 'HANSEN', 'CASTRO', 'HOFFMAN', 'HART', 'ELLIOTT', 'CUNNINGHAM', 'KNIGHT', 'BRADLEY', 'CARROLL', 'HUDSON', 'DUNCAN', 
        'ARMSTRONG', 'BERRY', 'ANDREWS', 'JOHNSTON', 'RAY', 'LANE', 'RILEY', 'CARPENTER', 'PERKINS', 'AGUILAR', 'SILVA', 'RICHARDS', 'WILLIS', 'MATTHEWS', 'CHAPMAN', 'LAWRENCE', 'GARZA', 'VARGAS', 'WATKINS', 'WHEELER', 
        'LARSON', 'CARLSON', 'HARPER', 'GEORGE', 'GREENE', 'BURKE', 'GUZMAN', 'MORRISON', 'MUNOZ', 'JACOBS', 'OBRIEN', 'LAWSON', 'FRANKLIN', 'LYNCH', 'BISHOP', 'CARR', 'SALAZAR', 'AUSTIN', 'MENDEZ', 'GILBERT', 'JENSEN', 
        'WILLIAMSON', 'MONTGOMERY', 'HARVEY', 'OLIVER', 'HOWELL', 'DEAN', 'HANSON', 'WEBER', 'GARRETT', 'SIMS', 'BURTON', 'FULLER', 'SOTO', 'MCCOY', 'WELCH', 'CHEN', 'SCHULTZ', 'WALTERS', 'REID', 'FIELDS', 'WALSH', 'LITTLE', 
        'FOWLER', 'BOWMAN', 'DAVIDSON', 'MAY', 'DAY', 'SCHNEIDER', 'NEWMAN', 'BREWER', 'LUCAS', 'HOLLAND', 'WONG', 'BANKS', 'SANTOS', 'CURTIS', 'PEARSON', 'DELGADO', 'VALDEZ', 'PENA', 'RIOS', 'DOUGLAS', 'SANDOVAL', 'BARRETT', 
        'HOPKINS', 'KELLER', 'GUERRERO', 'STANLEY', 'BATES', 'ALVARADO', 'BECK', 'ORTEGA', 'WADE', 'ESTRADA', 'CONTRERAS', 'BARNETT', 'CALDWELL', 'SANTIAGO', 'LAMBERT', 'POWERS', 'CHAMBERS', 'NUNEZ', 'CRAIG', 'LEONARD', 'LOWE', 
        'RHODES', 'BYRD', 'GREGORY', 'SHELTON', 'FRAZIER', 'BECKER', 'MALDONADO', 'FLEMING', 'VEGA', 'SUTTON', 'COHEN', 'JENNINGS', 'PARKS', 'MCDANIEL', 'WATTS', 'BARKER', 'NORRIS', 'VAUGHN', 'VAZQUEZ', 'HOLT', 'SCHWARTZ', 'STEELE', 
        'BENSON', 'NEAL', 'DOMINGUEZ', 'HORTON', 'TERRY', 'WOLFE', 'HALE', 'LYONS', 'GRAVES', 'HAYNES', 'MILES', 'PARK', 'WARNER', 'PADILLA', 'BUSH', 'THORNTON', 'MCCARTHY', 'MANN', 'ZIMMERMAN', 'ERICKSON', 'FLETCHER', 'MCKINNEY', 
        'PAGE', 'DAWSON', 'JOSEPH', 'MARQUEZ', 'REEVES', 'KLEIN', 'ESPINOZA', 'BALDWIN', 'MORAN', 'LOVE', 'ROBBINS', 'HIGGINS', 'BALL', 'CORTEZ', 'LE', 'GRIFFITH', 'BOWEN', 'SHARP', 'CUMMINGS', 'RAMSEY', 'HARDY', 'SWANSON', 'BARBER', 
        'ACOSTA', 'LUNA', 'CHANDLER', 'DANIEL', 'BLAIR', 'CROSS', 'SIMON', 'DENNIS', 'OCONNOR', 'QUINN', 'GROSS', 'NAVARRO', 'MOSS', 'FITZGERALD', 'DOYLE', 'MCLAUGHLIN', 'ROJAS', 'RODGERS', 'STEVENSON', 'SINGH', 'YANG', 'FIGUEROA', 
        'HARMON', 'NEWTON', 'PAUL', 'MANNING', 'GARNER', 'MCGEE', 'REESE', 'FRANCIS', 'BURGESS', 'ADKINS', 'GOODMAN', 'CURRY', 'BRADY', 'CHRISTENSEN', 'POTTER', 'WALTON', 'GOODWIN', 'MULLINS', 'MOLINA', 'WEBSTER', 'FISCHER', 'CAMPOS', 
        'AVILA', 'SHERMAN', 'TODD', 'CHANG', 'BLAKE', 'MALONE', 'WOLF', 'HODGES', 'JUAREZ', 'GILL', 'FARMER', 'HINES', 'GALLAGHER', 'DURAN', 'HUBBARD', 'CANNON', 'MIRANDA', 'WANG', 'SAUNDERS', 'TATE', 'MACK', 'HAMMOND', 'CARRILLO', 'TOWNSEND', 
        'WISE', 'INGRAM', 'BARTON', 'MEJIA', 'AYALA', 'SCHROEDER', 'HAMPTON', 'ROWE', 'PARSONS', 'FRANK', 'WATERS', 'STRICKLAND', 'OSBORNE', 'MAXWELL', 'CHAN', 'DELEON', 'NORMAN', 'HARRINGTON', 'CASEY', 'PATTON', 'LOGAN', 'BOWERS', 'MUELLER', 'GLOVER', 
        'FLOYD', 'HARTMAN', 'BUCHANAN', 'COBB', 'FRENCH', 'KRAMER', 'MCCORMICK', 'CLARKE', 'TYLER', 'GIBBS', 'MOODY', 'CONNER', 'SPARKS', 'MCGUIRE', 'LEON', 'BAUER', 'NORTON', 'POPE', 'FLYNN', 'HOGAN', 'ROBLES', 'SALINAS', 'YATES', 'LINDSEY', 'LLOYD', 'MARSH', 
        'MCBRIDE', 'OWEN', 'SOLIS', 'PHAM', 'LANG', 'PRATT', 'LARA', 'BROCK', 'BALLARD', 'TRUJILLO', 'SHAFFER', 'DRAKE', 'ROMAN', 'AGUIRRE', 'MORTON', 'STOKES', 'LAMB', 'PACHECO', 'PATRICK', 'COCHRAN', 'SHEPHERD', 'CAIN', 'BURNETT', 'HESS', 'LI', 'CERVANTES', 'OLSEN', 
        'BRIGGS', 'OCHOA', 'CABRERA', 'VELASQUEZ', 'MONTOYA', 'ROTH', 'MEYERS', 'CARDENAS', 'FUENTES', 'WEISS', 'WILKINS', 'HOOVER', 'NICHOLSON', 'UNDERWOOD', 'SHORT', 'CARSON', 'MORROW', 'COLON', 'HOLLOWAY', 'SUMMERS', 'BRYAN', 'PETERSEN', 'MCKENZIE', 'SERRANO', 'WILCOX', 
        'CAREY', 'CLAYTON', 'POOLE', 'CALDERON', 'GALLEGOS', 'GREER', 'RIVAS', 'GUERRA', 'DECKER', 'COLLIER', 'WALL', 'WHITAKER', 'BASS', 'FLOWERS', 'DAVENPORT', 'CONLEY', 'HOUSTON', 'HUFF', 'COPELAND', 'HOOD', 'MONROE', 'MASSEY', 'ROBERSON', 'COMBS', 'FRANCO', 'LARSEN', 'PITTMAN', 
        'RANDALL', 'SKINNER', 'WILKINSON', 'KIRBY', 'CAMERON', 'BRIDGES', 'ANTHONY', 'RICHARD', 'KIRK', 'BRUCE', 'SINGLETON', 'MATHIS', 'BRADFORD', 'BOONE', 'ABBOTT', 'CHARLES', 'ALLISON', 'SWEENEY', 'ATKINSON', 'HORN', 'JEFFERSON', 'ROSALES', 'YORK', 'CHRISTIAN', 'PHELPS', 'FARRELL', 
        'CASTANEDA', 'NASH', 'DICKERSON', 'BOND', 'WYATT', 'FOLEY', 'CHASE', 'GATES', 'VINCENT', 'MATHEWS', 'HODGE', 'GARRISON', 'TREVINO', 'VILLARREAL', 'HEATH', 'DALTON', 'VALENCIA', 'CALLAHAN', 'HENSLEY', 'ATKINS', 'HUFFMAN', 'ROY', 'BOYER', 'SHIELDS', 'LIN', 'HANCOCK', 'GRIMES', 
        'GLENN', 'CLINE', 'DELACRUZ', 'CAMACHO', 'DILLON', 'PARRISH', 'ONEILL', 'MELTON', 'BOOTH', 'KANE', 'BERG', 'HARRELL', 'PITTS', 'SAVAGE', 'WIGGINS', 'BRENNAN', 'SALAS', 'MARKS', 'RUSSO', 'SAWYER', 'BAXTER', 'GOLDEN', 'HUTCHINSON', 'LIU', 'WALTER', 'MCDOWELL', 'WILEY', 'RICH', 
        'HUMPHREY', 'JOHNS', 'KOCH', 'SUAREZ', 'HOBBS', 'BEARD', 'GILMORE', 'IBARRA', 'KEITH', 'MACIAS', 'KHAN', 'ANDRADE', 'WARE', 'STEPHENSON', 'HENSON', 'WILKERSON', 'DYER', 'MCCLURE', 'BLACKWELL', 'MERCADO', 'TANNER', 'EATON', 'CLAY', 'BARRON', 'BEASLEY', 'ONEAL', 'SMALL', 'PRESTON', 
        'WU', 'ZAMORA', 'MACDONALD', 'VANCE', 'SNOW', 'MCCLAIN', 'STAFFORD', 'OROZCO', 'BARRY', 'ENGLISH', 'SHANNON', 'KLINE', 'JACOBSON', 'WOODARD', 'HUANG', 'KEMP', 'MOSLEY', 'PRINCE', 'MERRITT', 'HURST', 'VILLANUEVA', 'ROACH', 'NOLAN', 'LAM', 'YODER', 'MCCULLOUGH', 'LESTER', 'SANTANA', 
        'VALENZUELA', 'WINTERS', 'BARRERA', 'ORR', 'LEACH', 'BERGER', 'MCKEE', 'STRONG', 'CONWAY', 'STEIN', 'WHITEHEAD', 'BULLOCK', 'ESCOBAR', 'KNOX', 'MEADOWS', 'SOLOMON', 'VELEZ', 'ODONNELL', 'KERR', 'STOUT', 'BLANKENSHIP', 'BROWNING', 'KENT', 'LOZANO', 'BARTLETT', 'PRUITT', 'BUCK', 'BARR', 
        'GAINES', 'DURHAM', 'GENTRY', 'MCINTYRE', 'SLOAN', 'ROCHA', 'MELENDEZ', 'HERMAN', 'SEXTON', 'MOON', 'HENDRICKS', 'RANGEL', 'STARK', 'LOWERY', 'HARDIN', 'HULL', 'SELLERS', 'ELLISON', 'CALHOUN', 'GILLESPIE', 'MORA', 'KNAPP', 'MCCALL', 'MORSE', 'DORSEY', 'WEEKS', 'NIELSEN', 'LIVINGSTON', 
        'LEBLANC', 'MCLEAN', 'BRADSHAW', 'GLASS', 'MIDDLETON', 'BUCKLEY', 'SCHAEFER', 'FROST', 'HOWE', 'HOUSE', 'MCINTOSH', 'HO', 'PENNINGTON', 'REILLY', 'HEBERT', 'MCFARLAND', 'HICKMAN', 'NOBLE', 'SPEARS', 'CONRAD', 'ARIAS', 'GALVAN', 'VELAZQUEZ', 'HUYNH', 'FREDERICK', 'RANDOLPH', 'CANTU', 
        'FITZPATRICK', 'MAHONEY', 'PECK', 'VILLA', 'MICHAEL', 'DONOVAN', 'MCCONNELL', 'WALLS', 'BOYLE', 'MAYER', 'ZUNIGA', 'GILES', 'PINEDA', 'PACE', 'HURLEY', 'MAYS', 'MCMILLAN', 'CROSBY', 'AYERS', 'CASE', 'BENTLEY', 'SHEPARD', 'EVERETT', 'PUGH', 'DAVID', 'MCMAHON', 'DUNLAP', 'BENDER', 'HAHN', 
        'HARDING', 'ACEVEDO', 'RAYMOND', 'BLACKBURN', 'DUFFY', 'LANDRY', 'DOUGHERTY', 'BAUTISTA', 'SHAH', 'POTTS', 'ARROYO', 'VALENTINE', 'MEZA', 'GOULD', 'VAUGHAN', 'FRY', 'RUSH', 'AVERY', 'HERRING', 'DODSON', 'CLEMENTS', 'SAMPSON', 'TAPIA', 'BEAN', 'LYNN', 'CRANE', 'FARLEY', 'CISNEROS', 
        'BENTON', 'ASHLEY', 'MCKAY', 'FINLEY', 'BEST', 'BLEVINS', 'FRIEDMAN', 'MOSES', 'SOSA', 'BLANCHARD', 'HUBER', 'FRYE', 'KRUEGER', 'BERNARD', 'ROSARIO', 'RUBIO', 'MULLEN', 'BENJAMIN', 'HALEY', 'CHUNG', 'MOYER', 'CHOI', 'HORNE', 'YU', 'WOODWARD', 'ALI', 'NIXON', 'HAYDEN', 'RIVERS', 'ESTES', 
        'MCCARTY', 'RICHMOND', 'STUART', 'MAYNARD', 'BRANDT', 'OCONNELL', 'HANNA', 'SANFORD', 'SHEPPARD', 'CHURCH', 'BURCH', 'LEVY', 'RASMUSSEN', 'COFFEY', 'PONCE', 'FAULKNER', 'DONALDSON', 'SCHMITT', 'NOVAK', 'COSTA', 'MONTES', 'BOOKER', 'CORDOVA', 'WALLER', 'ARELLANO', 'MADDOX', 'MATA', 
        'BONILLA', 'STANTON', 'COMPTON', 'KAUFMAN', 'DUDLEY', 'MCPHERSON', 'BELTRAN', 'DICKSON', 'MCCANN', 'VILLEGAS', 'PROCTOR', 'HESTER', 'CANTRELL', 'DAUGHERTY', 'CHERRY', 'BRAY', 'DAVILA', 'ROWLAND', 'MADDEN', 'LEVINE', 'SPENCE', 'GOOD', 'IRWIN', 'WERNER', 'KRAUSE', 'PETTY', 'WHITNEY', 
        'BAIRD', 'HOOPER', 'POLLARD', 'ZAVALA', 'JARVIS', 'HOLDEN', 'HENDRIX', 'HAAS', 'MCGRATH', 'BIRD', 'LUCERO', 'TERRELL', 'RIGGS', 'JOYCE', 'ROLLINS', 'MERCER', 'GALLOWAY', 'DUKE', 'ODOM', 'ANDERSEN', 'DOWNS', 'HATFIELD', 'BENITEZ', 'ARCHER', 'HUERTA', 'TRAVIS', 'MCNEIL', 'HINTON', 
        'ZHANG', 'HAYS', 'MAYO', 'FRITZ', 'BRANCH', 'MOONEY', 'EWING', 'RITTER', 'ESPARZA', 'FREY', 'BRAUN', 'GAY', 'RIDDLE', 'HANEY', 'KAISER', 'HOLDER', 'CHANEY', 'MCKNIGHT', 'GAMBLE', 'VANG', 'COOLEY', 'CARNEY', 'COWAN', 'FORBES', 'FERRELL', 'DAVIES', 'BARAJAS', 'SHEA', 'OSBORN', 
        'BRIGHT', 'CUEVAS', 'BOLTON', 'MURILLO', 'LUTZ', 'DUARTE', 'KIDD', 'KEY'); 
        
        RETURN last_name;

END; //

DELIMITER ;

DELIMITER //

CREATE PROCEDURE generate_random_transactions
(IN num_of_transactions INT)
BEGIN

	SET @i = 0;
    SET @user_count = (SELECT COUNT(*) FROM Accounts);
    WHILE @i <= num_of_transactions DO
		INSERT INTO Transactions VALUES
		(NULL, (FLOOR(1+ RAND()*100)), ELT(FLOOR(RAND()*2)+1, 'WITHDRAW', 'DEPOSIT'), get_random_date(25), FLOOR(1+RAND()*@user_count));
        SET @i = @i+1;
	END WHILE;

END; //

DELIMITER ;


DELIMITER //

CREATE PROCEDURE generate_random_accounts
(IN num_of_accounts INT)
BEGIN
	SET @i = 0;
    
    WHILE @i <= num_of_accounts DO
    
		INSERT INTO Accounts VALUES
			(NULL, CONCAT(get_first_name(''), ' ', get_last_name('')), (FLOOR(1+ RAND()*10000)), 0, CONCAT(get_first_name(''), get_last_name('')));
            
		SET @i = @i+1;
    
    END WHILE;


END; //

DELIMITER ;

CALL generate_random_accounts(25);
CALL generate_random_transactions(100);




/*
convenience procedure add_check_user added to create new user if username doesn't exist
or to add a transaction if the user already exists. 
here's two examples:
CALL add_check_user("John Smith", 50000, 'JohnnyBoy', 500, 'DEPOSIT');
CALL add_check_user("John Smith", 50000, 'JohnSmith', 500, 'DEPOSIT');

NOTE: in order to run FUNCTION get_random_date you must first run command
SET GLOBAL log_bin_trust_function_creators = 1;
then edit
C:\ProgramData\MySQL\MySQL Server 8.0\my.ini and add the flag
log_bin_trust_function_creators=1
finally restart mysql service then run sql script again

*/

